Repository feathr-ai/feathr, pull requests merged in 2022-07, with the labels that each got.

#404 New Purview Registry adapt Sql data model
  registry/purview-registry/.dockerignore
  registry/purview-registry/.gitignore
  registry/purview-registry/Dockerfile
  registry/purview-registry/README.md
  registry/purview-registry/api-spec.md
  registry/purview-registry/main.py
  registry/purview-registry/registry/__init__.py
  registry/purview-registry/registry/interface.py
  registry/purview-registry/registry/models.py
  registry/purview-registry/registry/purview_registry.py
  registry/purview-registry/requirements.txt
  registry/purview-registry/test/test_creation.py
  registry/purview-registry/test/test_get.py
Labels: safe to test

#409 Access Control Plugin for Registry APIs
  registry/Dockerfile
  registry/access_control/.env
  registry/access_control/README.md
  registry/access_control/__init__.py
  registry/access_control/access.py
  registry/access_control/auth.py
  registry/access_control/config.py
  registry/access_control/db_rbac.py
  registry/access_control/interface.py
  registry/access_control/models.py
  registry/access_control/scripts/schema.sql
  registry/access_control/scripts/test_data.sql
  registry/api.py
  registry/common/database.py
  registry/main.py
  registry/requirements.txt
  ui/src/api/api.tsx
  ui/src/api/mock/userrole.json
  ui/src/components/roleManagementForm.tsx
  ui/src/components/userRoles.tsx
  ui/src/models/model.ts
Labels: enhancement, safe to test

#397 Replace PurView client with Registry API client
  feathr_project/feathr/client.py
  feathr_project/feathr/definition/anchor.py
  feathr_project/feathr/definition/dtype.py
  feathr_project/feathr/definition/feature_derivations.py
  feathr_project/feathr/registry/_feathr_registry_client.py
  feathr_project/feathr/registry/_feature_registry_purview.py
  feathr_project/feathr/registry/feature_registry.py
  feathr_project/feathrcli/cli.py
  feathr_project/test/test_feature_registry.py
  feathr_project/test/test_registry_client.py
  feathr_project/test/test_registry_lineage.json
  feathr_project/test/test_user_workspace/feathr_config.yaml
Labels: safe to test

#400 Added local_folder param to get_result_df (#394)
  feathr_project/feathr/utils/job_utils.py
Labels: safe to test

#432 Fix purview search api
  registry/purview-registry/main.py
  registry/purview-registry/registry/purview_registry.py
Labels: safe to test

#438 Update access control config name to unique ones
  registry/Dockerfile
  registry/access_control/.env
  registry/access_control/README.md
  registry/access_control/__init__.py
  registry/access_control/api.py
  registry/access_control/config.py
  registry/access_control/main.py
  registry/access_control/rbac/__init__.py
  registry/access_control/rbac/access.py
  registry/access_control/rbac/auth.py
  registry/access_control/rbac/config.py
  registry/access_control/rbac/database.py
  registry/access_control/rbac/db_rbac.py
  registry/access_control/rbac/interface.py
  registry/access_control/rbac/models.py
  registry/access_control/requirements.txt
Labels: safe to test

#442 Use precondition to check mvcc conflict
  registry/purview-registry/registry/purview_registry.py
Labels: safe to test

#450 update config for better deployment experience
  registry/access_control/.env
  registry/access_control/main.py
  registry/access_control/rbac/auth.py
  registry/access_control/rbac/config.py
Labels: safe to test

#471 Fix token 400 bad request: popup second consent
  ui/src/api/api.tsx
Labels: bug, safe to test

#468 support aad application tokens
  registry/access_control/README.md
  registry/access_control/api.py
  registry/access_control/rbac/access.py
  registry/access_control/rbac/auth.py
  registry/access_control/rbac/models.py
Labels: safe to test

#482 Get project name from backend rather than param for access control plugin APIs
  registry/access_control/api.py
  registry/access_control/rbac/access.py
Labels: safe to test

#353 Added delete api of Redis
  feathr_project/feathr/client.py
  feathr_project/test/test_feature_materialization.py
Labels: safe to test

#499 Fixed redis_clint spelling error
  feathr_project/feathr/client.py
Labels: safe to test

#481 Optimize brand new Feathr typeDef registration
  registry/purview-registry/registry/purview_registry.py
Labels: safe to test

#459 Add Legacy workspace migration script
  feathr_project/feathr/constants.py
  registry/purview-registry/script/migrate_legacy_project.py
Labels: safe to test

#514 Enable azure cli generated token from client
  registry/access_control/rbac/auth.py
  registry/access_control/rbac/models.py
Labels: safe to test
