Repository feathr-ai/feathr, pull requests merged in 2022-06, with the labels that each got.

#303 Feathr UI: API spec alignment and ux experience improvement
  ui/.env
  ui/package-lock.json
  ui/package.json
  ui/src/api/api.tsx
  ui/src/api/mock/userrole.json
  ui/src/app.tsx
  ui/src/components/dataSourceList.tsx
  ui/src/components/featureForm.tsx
  ui/src/components/featureList.tsx
  ui/src/components/graph/graph.tsx
  ui/src/components/graph/graphNode.tsx
  ui/src/components/graph/utils.ts
  ui/src/components/lineage/layouting.css
  ui/src/components/lineage/lineage.tsx
  ui/src/components/roleManagementForm.tsx
  ui/src/components/sidemenu/siteMenu.tsx
  ui/src/components/userRoles.tsx
  ui/src/index.tsx
  ui/src/models/model.ts
  ui/src/pages/feature/featureDetails.tsx
  ui/src/pages/feature/featureLineage.tsx
  ui/src/pages/feature/features.tsx
  ui/src/pages/feature/lineageGraph.tsx
  ui/src/pages/management/management.tsx
  ui/src/pages/management/roleManagement.tsx
  ui/src/react-app-env.d.ts
  ui/src/router/routes.tsx
  ui/src/site.css
Labels: safe to test

#339 Feathr UI: Show feature details when click feature in lineage graph
  ui/src/components/graph/graph.tsx
  ui/src/components/graph/graphNodeDetails.tsx
  ui/src/pages/feature/lineageGraph.tsx
Labels: safe to test

#333 Optimize environment variable behavior
  docs/concepts/feathr-concepts-for-beginners.md
  docs/how-to-guides/feathr-configuration-and-env.md
  feathr_project/feathr/client.py
  feathr_project/feathr/secrets/akv_client.py
  feathr_project/feathr/spark_provider/_databricks_submission.py
  feathr_project/feathr/spark_provider/_synapse_submission.py
  feathr_project/feathr/utils/_envvariableutil.py
  feathr_project/feathrcli/data/feathr_user_workspace/feathr_config.yaml
  feathr_project/test/prep_azure_kafka_test_data.py
  feathr_project/test/test_secrets_read.py
Labels: safe to test

#337 enable JWT token param in frontend API calls
  ui/src/api/api.tsx
  ui/src/app.tsx
  ui/src/utils/utils.tsx
Labels: safe to test

#355 Quick fix the 404 link of "quick start guide" in readme.md
  README.md
Labels: bug, documentation

#357 add license, release, docs, python api ref badges with shields img
  README.md
Labels: documentation

#360 obejectId query cmd update
  docs/README.md
  docs/how-to-guides/azure-deployment.md
  docs/how-to-guides/azure_resource_provision.json
  docs/how-to-guides/deployment/deploy.json
  docs/how-to-guides/deployment/main.bicep
  docs/quickstart_synapse.md
  feathr_project/feathrcli/data/feathr_user_workspace/nyc_driver_demo.ipynb
  feathr_project/feathrcli/data/feathr_user_workspace/product_recommendation_demo.ipynb
Labels: bug, documentation

#363 add links to Azure Key Vault name convert logic in quick start guide.
  docs/how-to-guides/feathr-configuration-and-env.md
  docs/quickstart_synapse.md
Labels: documentation

#381 Feathr UI: fit lineage graph to center of layout view on page load
  ui/src/components/graph/graph.tsx
  ui/src/components/graph/graphNodeDetails.tsx
Labels: safe to test

#380 Refreshed JDBC support
  feathr_project/feathr/client.py
  feathr_project/feathr/definition/source.py
  feathr_project/feathr/registry/_feature_registry_purview.py
  feathr_project/feathr/spark_provider/_abc.py
  feathr_project/feathr/spark_provider/_databricks_submission.py
  feathr_project/feathr/spark_provider/_synapse_submission.py
  feathr_project/feathr/udf/_preprocessing_pyudf_manager.py
  feathr_project/test/test_sql_source.py
  project/build.properties
  src/main/java/com/linkedin/feathr/common/util/MvelContextUDFs.java
  src/main/scala/com/linkedin/feathr/offline/config/FeathrConfigLoader.scala
  src/main/scala/com/linkedin/feathr/offline/config/location/InputLocation.scala
  src/main/scala/com/linkedin/feathr/offline/config/location/Jdbc.scala
  src/main/scala/com/linkedin/feathr/offline/config/location/KafkaEndpoint.scala
  src/main/scala/com/linkedin/feathr/offline/config/location/PathList.scala
  src/main/scala/com/linkedin/feathr/offline/config/location/SimplePath.scala
  src/main/scala/com/linkedin/feathr/offline/job/FeatureGenJob.scala
  src/main/scala/com/linkedin/feathr/offline/job/FeatureJoinJob.scala
  src/main/scala/com/linkedin/feathr/offline/source/accessor/NonTimeBasedDataSourceAccessor.scala
  src/main/scala/com/linkedin/feathr/offline/source/dataloader/BatchDataLoader.scala
  src/main/scala/com/linkedin/feathr/offline/source/dataloader/hdfs/FileFormat.scala
  src/main/scala/com/linkedin/feathr/offline/transformation/AnchorToDataSourceMapper.scala
  src/test/scala/com/linkedin/feathr/offline/config/TestDataSourceLoader.scala
Labels: safe to test

#383 Fix Python doc links in Docs and add `HdfsSink` back
  docs/concepts/feature-definition.md
  docs/concepts/feature-generation.md
  docs/concepts/feature-join.md
  docs/dev_guide/update_python_docs.md
  feathr_project/feathr/__init__.py
Labels: bug, documentation

#385 Feathr UI: remove delete button
  ui/src/api/api.tsx
  ui/src/components/featureList.tsx
  ui/src/pages/feature/featureDetails.tsx
Labels: safe to test

#379 Containerizing ui and rest backend into one docker image
  Dockerfile
  deploy/env.sh
  deploy/nginx.conf
  docs/how-to-guides/build-and-push-feathr-registry-docker-image.md
  ui/.env
  ui/Dockerfile
  ui/package-lock.json
  ui/public/env-config.js
  ui/public/index.html
  ui/src/api/api.tsx
  ui/src/index.tsx
  ui/src/models/model.ts
  ui/src/react-app-env.d.ts
  ui/src/utils/utils.tsx
Labels: safe to test

#411 Remove unnecessary Keywords in Docs and Fix typos
  docs/_config.yml
  docs/concepts/feathr-capabilities.md
  docs/concepts/feathr-concepts-for-beginners.md
  docs/concepts/feature-definition.md
  docs/concepts/feature-join.md
  docs/concepts/point-in-time-join.md
  docs/dev_guide/cloud_integration_testing.md
  docs/dev_guide/cloud_resource_provision.md
  docs/dev_guide/dev-guide.md
  docs/dev_guide/dev_testing_guide.md
  docs/dev_guide/doc_guide.md
  docs/dev_guide/feathr_overall_release_guide.md
  docs/dev_guide/publish_to_maven.md
  docs/dev_guide/pull_request_guideline.md
  docs/dev_guide/python_dev_guide.md
  docs/dev_guide/python_package_release.md
  docs/dev_guide/scala_dev_guide.md
  docs/dev_guide/update_python_docs.md
  docs/how-to-guides/azure-deployment.md
  docs/how-to-guides/build-and-push-feathr-registry-docker-image.md
  docs/how-to-guides/deploy-feathr-api-as-webapp.md
  docs/how-to-guides/expression-language.md
  docs/how-to-guides/feathr-configuration-and-env.md
  docs/how-to-guides/feathr-job-configuration.md
  docs/how-to-guides/how-to-guides.md
  docs/how-to-guides/local-feature-testing.md
  docs/how-to-guides/streaming-source-ingestion.md
  docs/how-to-guides/troubleshoot-feature-definition.md
  docs/quickstart_databricks.md
  docs/quickstart_synapse.md
Labels: documentation
