Repository feathr-ai/feathr, pull requests merged in 2023-01, with the labels that each got.

#919 Support get online features by composite keys
  feathr_project/feathr/client.py
  feathr_project/test/test_azure_spark_e2e.py
  feathr_project/test/test_fixture.py
Labels: safe to test

#940 fix numpy version conflict w/ pyspark
  feathr_project/setup.py
Labels: safe to test

#917 Add FIRST aggregation for look up feature
  feathr-impl/src/main/java/com/linkedin/feathr/common/FeatureAggregationType.java
  feathr-impl/src/main/scala/com/linkedin/feathr/offline/derived/strategies/SequentialJoinAsDerivation.scala
  feathr-impl/src/test/resources/anchor1-obs.csv
  feathr-impl/src/test/resources/anchor1-source-lookup.csv
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/LookupFeatureIntegTest.scala
  feathr_project/feathr/definition/aggregation.py
Labels: safe to test

#921 Update sample notebooks (fraud detection and recommendation examples) to use latest feathr api
  docs/images/cognitive-search-enrichment-architecture.png
  docs/samples/azure_synapse/product_recommendation_demo.ipynb
  docs/samples/databricks/databricks_quickstart_nyc_taxi_demo.ipynb
  docs/samples/document_intelligence_with_azure_cognitive_search_skills.ipynb
  docs/samples/feature_embedding.ipynb
  docs/samples/fraud_detection_demo.ipynb
  docs/samples/nyc_taxi_demo.ipynb
  docs/samples/product_recommendation_demo_advanced.ipynb
  feathr_project/feathr/client.py
  feathr_project/feathr/datasets/__init__.py
  feathr_project/feathr/datasets/constants.py
  feathr_project/feathr/utils/config.py
  feathr_project/test/samples/test_notebooks.py
Labels: safe to test

#937 Add pytest cases and check test coverage for sql-registry and purview…
  .github/workflows/pull_request_push_test.yml
  registry/purview-registry/main.py
  registry/purview-registry/registry/interface.py
  registry/purview-registry/registry/models.py
  registry/purview-registry/registry/purview_registry.py
  registry/sql-registry/main.py
  registry/sql-registry/registry/database.py
  registry/sql-registry/registry/db_registry.py
  registry/sql-registry/registry/interface.py
  registry/sql-registry/registry/models.py
  registry/sql-registry/requirements.txt
  registry/test/.coveragerc
  registry/test/requirements.txt
  registry/test/run_test_cases.sh
  registry/test/test_purview_registry.py
  registry/test/test_sql_registry.py
Labels: registry test

#952 Fix delete entity function bug for #852
  registry/access_control/api.py
Labels: safe to test

#948 Bug fix - Fraud detection sample notebook chart error.
  docs/samples/fraud_detection_demo.ipynb
  docs/samples/product_recommendation_demo_advanced.ipynb
Labels: safe to test

#963 Changed !pip to %pip
  docs/samples/azure_synapse/product_recommendation_demo.ipynb
  docs/samples/databricks/databricks_quickstart_nyc_taxi_demo.ipynb
  docs/samples/document_intelligence_with_azure_cognitive_search_skills.ipynb
  docs/samples/feature_embedding.ipynb
  docs/samples/fraud_detection_demo.ipynb
  docs/samples/nyc_taxi_demo.ipynb
  docs/samples/product_recommendation_demo_advanced.ipynb
Labels: safe to test

#966 Add a Sandbox for Feathr
  .github/workflows/docker-publish.yml
  FeathrSandbox.Dockerfile
  docker/Dockerfile
  docker/supervisord.conf
  docs/how-to-guides/feathr-configuration-and-env.md
  docs/images/feathr-sandbox-dev-experience.png
  docs/images/feathr-sandbox-lineage.png
  docs/images/feathr-sandbox-ui.png
  docs/images/feathr-sandbox.png
  docs/quickstart_local_sandbox.md
  docs/samples/local_quickstart_notebook.ipynb
  feathr-sandbox/feathr_init_script.py
  feathr-sandbox/start_local.sh
  feathr_project/feathr/client.py
  feathr_project/feathr/registry/_feathr_registry_client.py
  feathr_project/feathr/spark_provider/_localspark_submission.py
  feathr_project/feathr/utils/_env_config_reader.py
  feathr_project/feathrcli/data/feathr_user_workspace/feathr_config.yaml
  feathr_project/setup.py
  feathr_project/test/test_user_workspace/feathr_config.yaml
  feathr_project/test/test_user_workspace/feathr_config_local.yaml
  feathr_project/test/test_user_workspace/feathr_config_maven.yaml
  registry/sql-registry/registry/database.py
  registry/sql-registry/registry/db_registry.py
  registry/sql-registry/requirements.txt
Labels: registry test

#979 Updating automated maven publish workflow to work with gradle creds
  .github/workflows/publish-to-maven.yml
Labels: safe to test

#988 Fix local submission issues.
  feathr_project/feathr/client.py
  feathr_project/feathr/spark_provider/_localspark_submission.py
Labels: safe to test

#972 Adding azure-cosmos-package to databricks spark config
  .github/workflows/pull_request_push_test.yml
  build.gradle
  feathr-impl/build.gradle
Labels: safe to test

#991 NYC sample notebook feature re-name
  docs/images/feature_flow.png
  docs/samples/nyc_taxi_demo.ipynb
Labels: safe to test

#1002 Revert "Adding azure-cosmos-package to databricks spark config"
  .github/workflows/pull_request_push_test.yml
  build.gradle
  feathr-impl/build.gradle
Labels: DO-NOT-MERGE

#984 Update fraud detection sample notebook
  docs/samples/fraud_detection_demo.ipynb
  feathr_project/test/samples/test_notebooks.py
Labels: safe to test

#1001 Add additional maven repo url to databricks submission param
  feathr_project/feathr/spark_provider/_databricks_submission.py
Labels: safe to test

#1004 Hard code json-schema dependency with comment as hot fix
  feathr_project/feathr/spark_provider/_databricks_submission.py
Labels: safe to test

#999 Remove use_env_vars arg from FeathrCient
  docs/samples/feature_embedding.ipynb
  feathr_project/feathr/client.py
  feathr_project/feathr/utils/_env_config_reader.py
  feathr_project/feathr/utils/config.py
  feathr_project/test/unit/utils/test_env_config_reader.py
Labels: safe to test

#992 Resolve pyspark / numpy conflicts
  docs/samples/databricks/databricks_quickstart_nyc_taxi_demo.ipynb
  docs/samples/nyc_taxi_demo.ipynb
  feathr_project/setup.py
Labels: safe to test

#930 Add retry when data loading fails
  build.gradle
  feathr-impl/build.gradle
  feathr-impl/src/main/scala/com/linkedin/feathr/offline/source/dataloader/BatchDataLoader.scala
  feathr-impl/src/test/java/com/linkedin/feathr/common/AutoTensorizableTypesTest.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/FeatureTypeConfigTest.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/TestFeatureDependencyGraph.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/TestFeatureValue.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/types/TestFeatureTypes.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/types/TestQuinceFeatureTypeMapper.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/util/MvelUDFExpressionTests.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/util/TestMvelContextUDFs.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/value/TestFeatureValueOldAPICompatibility.java
  feathr-impl/src/test/java/com/linkedin/feathr/common/value/TestFeatureValues.java
  feathr-impl/src/test/java/com/linkedin/feathr/offline/TestMvelContext.java
  feathr-impl/src/test/java/com/linkedin/feathr/offline/TestMvelExpression.java
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/FeathrIntegTest.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/SlidingWindowAggIntegTest.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/TestFeathr.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/TestFeathrUtils.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/client/TestDataFrameColName.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/config/TestDataSourceLoader.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/config/TestFeatureGroupsGenerator.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/config/TestFeatureJoinConfig.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/config/location/TestDesLocation.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/derived/TestSequentialJoinAsDerivation.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/generation/TestFeatureGenFeatureGrouper.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/generation/TestFeatureGenKeyTagAnalyzer.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/generation/TestIncrementalAggSnapshotLoader.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/generation/TestPostGenPruner.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/generation/TestPushToRedisOutputProcessor.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/generation/TestStageEvaluator.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/job/TestFeatureJoinJob.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/job/TestFeatureJoinJobUtils.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/job/TestFeatureTransformation.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/job/featureGen/TestFeatureGenConfigOverrider.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/job/featureGen/TestFeatureGenJobParser.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/job/featureGen/TestFeatureGenSpecParser.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/join/algorithms/TestJoinConditionBuilder.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/join/algorithms/TestJoinKeyColumnsAppender.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/join/algorithms/TestSparkJoin.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/join/algorithms/TestSparkSaltedJoin.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/join/workflow/TestAnchoredFeatureJoinStep.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/join/workflow/TestDerivedFeatureJoinStep.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/logical/TestMultiStageJoinPlan.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/source/dataloader/TestBatchDataLoader.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/source/dataloader/TestCaseInsensitiveGenericRecordWrapper.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/source/pathutil/TestPathChecker.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/source/pathutil/TestTimeBasedHdfsPathAnalyzer.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/source/pathutil/TestTimeBasedHdfsPathGenerator.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/swa/TestSlidingWindowFeatureUtils.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/transformation/TestAnchorToDataSourceMapper.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/transformation/TestDataFrameExt.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/transformation/TestDefaultValueToColumnConverter.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/transformation/TestFDSConversionUtils.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/util/TestDataFrameSplitterMerger.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/util/TestFDSConversionUtil.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/util/TestPartitionLimiter.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/util/datetime/TestDateTimeInterval.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/util/datetime/TestDateTimePeriod.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/util/datetime/TestOfflineDateTimeUtils.scala
Labels: safe to test

#939 Adding CosmosDb as supported Online Store from deployment template
  docs/how-to-guides/azure_resource_provision.json
Labels: safe to test

#1013 Adding documentation for azure.cosmos.spark package and managing spark libraries
  docs/how-to-guides/jdbc-cosmos-notes.md
  docs/how-to-guides/manage-library-spark-platform.md
Labels: safe to test

#1012 Adding dummy entries to feathr_config.yaml file for additional library entries
  feathr_project/feathr/spark_provider/_databricks_submission.py
  feathr_project/feathrcli/data/feathr_user_workspace/feathr_config.yaml
  feathr_project/test/test_user_workspace/feathr_config.yaml
Labels: safe to test

#1015 Adding guidance for picking optimal SKU for Azure SQL DB
  docs/how-to-guides/feathr-azure-sql-guidance.md
  docs/images/azure-sql-db-compute-storage.png
  docs/images/azure-sql-db-hardware-configs.png
  docs/images/azure-sql-default-configs.png
Labels: safe to test

#1011 Refactor config helper to be cleaner
  .github/workflows/pull_request_push_test.yml
  feathr_project/feathr/spark_provider/_localspark_submission.py
  feathr_project/feathr/utils/_env_config_reader.py
  feathr_project/test/unit/utils/test_env_config_reader.py
Labels: safe to test

#1019 Skip features optionally if feature data is missing
  feathr-impl/src/main/scala/com/linkedin/feathr/offline/swa/SlidingWindowAggregationJoiner.scala
  feathr-impl/src/main/scala/com/linkedin/feathr/offline/transformation/AnchorToDataSourceMapper.scala
  feathr-impl/src/main/scala/com/linkedin/feathr/offline/util/FeathrUtils.scala
  feathr-impl/src/test/scala/com/linkedin/feathr/offline/SlidingWindowAggIntegTest.scala
  gradle.properties
Labels: safe to test
